### ISSUE TITLE
新しいZoomキャプチャの構成図を作成する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#110]

**Comment by jacopen** [comment]
描いた
https://miro.com/app/board/uXjVOQQhzXI=/?moveToWidget=3458764520286928902&cot=14

レビューして問題無ければクローズで @TakumaNakagame

**Comment by TakumaNakagame** [comment]
OKです！
すごくいいです、ありがとうございます！
