### ISSUE TITLE
必要なものの買い物

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#115]
会場設営に買っておきたいもの

- [x] 養生テープ
- [x] マッキー
- [x] 付箋
- [x] 示名条片
- [x] ケーブル結束バンド
- [x] 光HDMI 1本 (40m)
- [x] 10m LANケーブル(3本) 
- [x] LANのメス-メスのコネクタ (2つ)

**Comment by jacopen** [comment]
![image](https://user-images.githubusercontent.com/79102/156622737-928aaa40-ffd9-4ef8-94b3-901000b01ca3.png)
![image](https://user-images.githubusercontent.com/79102/156622761-b5944d18-530c-4747-9b77-c516e761cc83.png)
