### ISSUE TITLE
動画ファイル差し替え

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-broadcast#13]
動画ファイルを元ソースに差し替えたので、再ダウンロードして差し替えをお願いします

Kubernetes-native な管理をおこなう CI_CD 2020.mp4
https://dreamkast-public-bucket.s3-ap-northeast-1.amazonaws.com/preevent/Kubernetes-native+%E3%81%AA%E7%AE%A1%E7%90%86%E3%82%92%E3%81%8A%E3%81%93%E3%81%AA%E3%81%86+CI_CD+2020.mp4

とある少人数のサービス開発チームのクラウドネイティブへの船出の話.mp4  (これは変更なし)
https://dreamkast-public-bucket.s3-ap-northeast-1.amazonaws.com/preevent/%E3%81%A8%E3%81%82%E3%82%8B%E5%B0%91%E4%BA%BA%E6%95%B0%E3%81%AE%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%E9%96%8B%E7%99%BA%E3%83%81%E3%83%BC%E3%83%A0%E3%81%AE%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%89%E3%83%8D%E3%82%A4%E3%83%86%E3%82%A3%E3%83%96%E3%81%B8%E3%81%AE%E8%88%B9%E5%87%BA%E3%81%AE%E8%A9%B1.mp4

攻撃しながら考えるKubernetesのセキュリティ.mp4
https://dreamkast-public-bucket.s3-ap-northeast-1.amazonaws.com/preevent/%E6%94%BB%E6%92%83%E3%81%97%E3%81%AA%E3%81%8C%E3%82%89%E8%80%83%E3%81%88%E3%82%8BKubernetes%E3%81%AE%E3%82%BB%E3%82%AD%E3%83%A5%E3%83%AA%E3%83%86%E3%82%A3.mp4

世界に誇れるプラットフォームチームをつくる.mp4
https://dreamkast-public-bucket.s3-ap-northeast-1.amazonaws.com/preevent/%E4%B8%96%E7%95%8C%E3%81%AB%E8%AA%87%E3%82%8C%E3%82%8B%E3%83%97%E3%83%A9%E3%83%83%E3%83%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E3%83%81%E3%83%BC%E3%83%A0%E3%82%92%E3%81%A4%E3%81%8F%E3%82%8B.mp4

**Comment by chago0419** [comment]
snapshot 作成しました
snapshot id: snap-02a55e7cb2bc7c66c
