### ISSUE TITLE
StreamYardのアカウント作成

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-broadcast#29]
CI/CD ConferenceやCNDT2021では、StreamYardというサービスを使って配信オペレーションをする可能性が高い。

https://streamyard.com/

事前にBroadcastチームとDreamkastチームでStreamYardを検証していきたいので、アカウントが欲しい。

## このチケットでやること
- [x] StreamYardのアカウントを1つ作る (dreamkast01@example.com　的なやつ)
- [x] Basicプランの月額課金に申し込む
- [x] StreamYardからのメールを必要なメンバーが受け取れるようにする

## このチケットのスコープ外だが、いずれは必要になること
- Professionalプランにアップグレード
- トラック数分アカウントを契約
  - なのでアカウント名、メールアドレスは連番であるほうが嬉しい

**Comment by jacopen** [comment]
メアドどうするか考えないといけない

**Comment by jyoshise** [comment]
Basic Plan (Monthly) へのアップグレードだん。

**Comment by jyoshise** [comment]
- dreamkast01@gafa.co.jp～dreamkast06@gafa.co.jp のグループ作成済み
- dreamkast01@gafa.co.jpに @jacopen と @TakumaNakagame 登録済み
- StreamYardのとりあえずアカウントのE-Mailをdreamkast01@gafa.co.jpにした
これで @jacopen と @TakumaNakagame はStreamYardにdreamkast01@gafa.co.jpでログインするための認証コードを受け取れるはず。以降同様でよいかな
