### ISSUE TITLE
StreamYardのアカウントを追加

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-broadcast#30]
#29 の続き

最終的に3トラックで配信することになったので、アカウントが計3つ必要となった。
#29 で1つ作成しているので、残り2を作成する

## このチケットでやること
- [x] MLを追加する (dreamkast02@gafa.co.jp, dreamkast03@gafa.co.jp) かつ必要なメンバーが受け取れるようにする
- [x] 作成したMLアドレスを使って、StreamYardのアカウントを作成
- [x] 上記のアカウントにProfessionalプランの月額課金に申し込む
- [x] dreamkast01アカウントをBasicからProfessionalにアップグレードする

メンバーが追加になったのでメールアドレスは別途送付します

**Comment by jyoshise** [comment]
done。ごかくにんください

**Comment by jacopen** [comment]
確認できました！ありがとうございます
