### ISSUE TITLE
SSOTなルートのドキュメントを作る

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-broadcast#31]
CI/CDの振り返りで出た内容。
CI/CDでは情報が分散してたどるのが大変だったので、すべてのドキュメントの起点になるルートのドキュメントを作成する

**Comment by jacopen** [comment]
Broadcast/CNDT2021 配下に作ってみた。
これにどんどん情報を追記していく形でいいかな？ 内容が多くなるものについては別Docsなりスプシなりを作ってここにリンクを張るイメージ。
https://docs.google.com/document/d/1gvA0oinngpFLKyYdB1Hq-ftkPO9VrK_SSJDU0xCnW34/edit

これでイメージとあっていればこのIssue終了しちゃってください  @TakumaNakagame

**Comment by TakumaNakagame** [comment]
よさそうですね
一瞬GitHubも考えたけど、パブリックに公開できないものもあるので、Google Docsで良さそうですね。
これでいきましょう。
