### ISSUE TITLE
バックパネルを導入できないか検討する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-broadcast#36]
CODTでは撮影会場にバックパネルを導入していて、イベントとしての見栄えが大分良かったので、同様のパネルを導入できないか

![image (12)](https://user-images.githubusercontent.com/79102/132907448-b11b3029-d294-4929-8f1c-a4687baadcba.png)
![image (13)](https://user-images.githubusercontent.com/79102/132907453-636b3fac-1275-46e3-8141-097ef4794444.png)

高価なスタジオを使っているのではなく、普通の会議室で実現出来ている様子(カメラのグレードは高いが)
https://twitter.com/axlltd/status/1431078487469674496

- 同様のパネルを導入する場合、どのくらいの予算が必要か
- 制作に必要なリードタイムはどのくらいか
- 使い終わったあとどこに仕舞うか

**Comment by jacopen** [comment]
https://www.ogata-print.com/prints/booth_back_panel_l#set

価格は10万くらい、納期は輸送時間込みでだいたい1週間くらいかなぁ

**Comment by suzukin** [comment]
JKDのときに2個作りました（厳密には布3枚と本体2個）インプレスの備品倉庫に残ってる気がします。ちなみに他のイベントでも使うので本体はたくさんあって布だけ交換すれば使い回せるようになってますが、コロナ渦でどうなってるかは要確認だと思います。
https://www.youtube.com/watch?v=r4InXz1AquA

**Comment by jacopen** [comment]
おおー、ありがとうございます。本体があるならコストも下げられそうですね。
発注するには大きさを確認しておく必要があるので、伊藤さんに確認して貰うのがよさそうかな。発注時の情報(発注先と発注内容)があればいいのですが・・・

**Comment by jacopen** [comment]
少なくともCNDT2021では要らない方向になったので閉じます
