### ISSUE TITLE
スライドのどこに登壇者をかぶせるのか決める

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#40]
## 概要
StreamYardを使ったときは気にしなかったけど、今回はスライド上に登壇者のカメラ映像が被る可能性が高い。
その場合、どこにかぶるのか事前に登壇者に通知し、該当箇所にコンテンツを配置しないように通知する必要がある。

基本的には、`右下` か `右上` のどちらかになるのではと。

**Comment by TakumaNakagame** [comment]
まず、スライドのコンテンツとしては次のような傾向がある

- `左上` は見出しが入ることが多い
- `左下` はコンテンツが上からそのまま入る？
- `右上` は特になし？
- `右下` はページ番号や引用元が入ることが多い

`左上` と `右下` はNG、 `左下` もコンテンツ領域が減ってしまうため、 `右上` が良いのでは

**Comment by jacopen** [comment]
被せるなら右上っていうのは賛成

あとそもそも表示領域を狭くして被らせないっていう選択肢もあるよね(SYと同じ方式)

**Comment by TakumaNakagame** [comment]
> あとそもそも表示領域を狭くして被らせないっていう選択肢もあるよね(SYと同じ方式)

ですね。
ただ、この制御をこっちのシステムでやるの意外と難しいので、潔くかぶせちゃうほうが楽かなって
たとえば、16:9なスライドならOBSとかで作ればええんですけど、この解像度が変わったときに地味に挙動が変わったり、極端に小さくなって見にくくなるとあれかなって
そのへんのハンドリングはしたくないので、かぶせる方向でいいかなと思いました

**Comment by TakumaNakagame** [comment]
右上で確定
