### ISSUE TITLE
配信検証する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#43]
オフラインでの検証を実施する
なお、参加にあたって、**ワクチン摂取が2回目まで完了**していること

## 決めること
- [x] 参加メンバー
- [x] もちもの
- [x] やること

**Comment by TakumaNakagame** [comment]
現地は、インターネット回線があり、電源タップはあるがそれ以外の機材はないので基本持ち込みとなる。

**Comment by TakumaNakagame** [comment]
持っていけるものとしては次の通り
- @jacopen : Windows2台(Laptop & DeskMini)
- @TakumaNakagame : 最低2台（Windows , Linux）、あとベアボーンのデスクトップ

**Comment by TakumaNakagame** [comment]
行くメンバーは次の通り
@TakumaNakagame , @jacopen , @Gaku-Kunimi , @KaseiKondo 

当日は、現地に10時集合で

**Comment by jacopen** [comment]
こちらも終わってるのでクローズ
