### ISSUE TITLE
TeamsのNDIを検証する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#44]
## 概要

以下のような、TeamsにてNDIを利用したい。
これについて、調査検証する。
https://support.microsoft.com/ja-jp/office/ndi-%E3%83%86%E3%82%AF%E3%83%8E%E3%83%AD%E3%82%B8%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9F-teams-%E3%81%8B%E3%82%89%E3%81%AE%E3%82%AA%E3%83%BC%E3%83%87%E3%82%A3%E3%82%AA%E3%81%A8%E3%83%93%E3%83%87%E3%82%AA%E3%81%AE%E6%94%BE%E9%80%81-e91a0adb-96b9-4dca-a2cd-07181276afa3

## やること

- [x] どのプランで利用できるのか
- [x] Microsoft 365 Business Basicの契約
- [x] TeamsのNDI設定
- [x] 試験用PCの用意 - Teams, NDI Tools, OBS, obs-ndiのセットアップ
- [x] 試験用PCでTeams meetingをホスト
- [x] 参加者想定PCからTeamsログイン(ブラウザ、アプリ)
- [x] 試験用PCのOBSで参加者のカメラと画面共有をNDI Sourceで受け取れるかどうか確認

### 詳細
Teamsを利用しているPCで、同じくOBSを起動し、OBSからNDI Sourceとして入力可能かどうか検証する

**Comment by suzukin** [comment]
Teams NDIだとMVPの胡田さんの動画が参考になると思います。
https://www.youtube.com/watch?v=F7oqzQ6w1Cs

**Comment by jacopen** [comment]
こちら終わってるのでクローズ
