### ISSUE TITLE
10/21 の事前収録セッション動画提出が間に合わない人をいつまでOKとするか

### ISSUE THREAD

**Issue by KaseiKondo** [cloudnativedaysjp/dreamkast-broadcast#48]
10/21提出期限のセッション動画について、今後間に合わないんですいつまでに出せばいいですか？という質問が来ることが予想されます。スポンサーについてはすでに1社来ています。

週末はさむ形で10/26(火)まででどうでしょうか？それ以上は基本NG。

@TakumaNakagame @jacopen 

due: 2021/09/28

**Comment by KaseiKondo** [comment]
@TakumaNakagame @jacopen こちらいかがでしょうか？　もう一社スポンサーから同様の問合せが来ています。

**Comment by TakumaNakagame** [comment]
私はそちらでいいと思いますー

**Comment by KaseiKondo** [comment]
ありがとうございます。では、**最終デッドが26日それ以降は受け付けません**、で統一したいと思います。
