### ISSUE TITLE
【プレイベント】oViceのキャプチャ対応

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#53]
https://github.com/cloudnativedaysjp/cndt2021/issues/48

**Comment by suzukin** [comment]
このキャプチャをアーカイブしてもらうことは可能でしょうか？ 今日のPromoミーティングでコンテンツとして再利用できないかというアイデアが出ました。MustではなくBetterくらいです。

**Comment by TakumaNakagame** [comment]
こちらの認識では、音声なしの画面のみのキャプチャということだったのですが、こちらをアーカイブするということですか？
アーカイブしても特に音声がない状態になるかと思うので、そちらの認識が間違っていないか確認です。

https://github.com/cloudnativedaysjp/cndt2021/issues/48#issuecomment-931805183

**Comment by suzukin** [comment]
こちら処理が煩雑になると思うので手元で別途キャプチャしようと思います、ので配信に専念いただけると！
