### ISSUE TITLE
18日 プレイベント内容検討

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#56]
決めること
- オペレーション担当者
- 配信の仕組みや構築すべきもの
- 当日必要なもの
- 当日やりたいこと/やれること/やれないこと

**Comment by TakumaNakagame** [comment]
2021/10/17 メモ

幕間動画の内容
- 基本情報
  - 日時
  - テーマ
  - ハッシュタグ
  - 無料
- キーノートタイトル
- 注目セッション

**Comment by suzukin** [comment]
@TakumaNakagame 

絵はブラウザ画面を全画面キャプチャしてオーバーレイで以下を入れるイメージです。BGM、音声はなしで構いません、oViceへの誘導としてDkでチラ見せしたいです。

```
oViceでパネルトーク & 書籍抽選大会実施中！
https://cnd.ovice.in/
```

https://github.com/cloudnativedaysjp/cndt2021/issues/48
