### ISSUE TITLE
当日のリモート登壇者対応のメンバーを確認する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#57]
Zoomでのリモート登壇の登壇者の対応をするメンバーを確定する
候補としては、オペレーションチームとなっている。

メンバー数： 2名

やることは次の通り
- 当日は現地スタジオへ行く
  - 場所は白金高輪駅周辺
  - 参加日は以下の通り
    - 本番： 11月4日/5日
    - リハーサル： 11月24日
- Zoomに参加した登壇者の対応/案内を行う
- 登壇者が適切に音声/カメラ/画面共有などができることを確認/案内する
- 登壇完了後の登壇者に、Ask the Speakerなどの案内を行う

**Comment by tsukaman** [comment]
スケジュールについて、了解致しました。
2名をアサインしつつ、4日は1名稼働＆1名バックアップとし、5日は2名稼働で回そうと思います。
5日のバックアップは鍋島さんにお願いする方向に倒していますが、もう1名アサインできそうであれば追加したいと思います。
