### ISSUE TITLE
GPU EC2インスタンスでのOBSテスト

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#6]
OBSを動かすにあたって、GPUインスタンスの検証を行う。

## 動作要件
- 1080p60のローカル動画ファイルを再生できること
  - OBSのメディアソースを利用
- 1080p60でYouTubeやVimeoに配信し、チラツキなどがなく再生できること
- 複数のシーンの切り替え操作が正常に行えること
  - セッション動画（5分～40分、単一動画）
  - CM（詳細未定、複数動画）

## 要求する成果物
- [x] 動作可能なインスタンスタイプをいくつかリストアップ
- [x] 対象のインスタンスタイプのコスト
  - [ ] 1080p/60 での配信時のコストまで含めて取れると神
- [ ] 配信時のパフォーマンス

**Comment by TakumaNakagame** [comment]
通常のWindows Server AMIでは、NVIDIAのドライバがデフォルトでインストールされていない。
https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html

代わりに、デフォルトでインストール済みのAMIがあるのでそちらを利用する。
https://aws.amazon.com/marketplace/pp/B07STLTHM8?qid=1612448836952&sr=0-7&ref_=srh_res_product_title

**Comment by TakumaNakagame** [comment]
インスタンスの候補
- g4dn (Tensor Core)
- p3 (Tesla)

**Comment by TakumaNakagame** [comment]
`Audiosrv`が無効化されていたので、有効化の必要あり

**Comment by TakumaNakagame** [comment]
自動化の観点から、WindowsよりもLinuxを推奨したい
Windowsでの動作検証を行った後、Linux Desktop(Ubuntu)での検証も実施する。

**Comment by fsatoru** [comment]
Ubuntu 20.04 にて EC2インスタンスで OBSの配信に成功したが
g4dn.xlarge では YouTube側で動画がガタついた為 g4dn.2xlarge にて再度検証した結果 問題なく視聴が出来た

金銭面的にやや問題があるため GCP等他の方法を検討中？
gnomeをGPU上で動かそうとしたが進まず

shellとOBSの設定ファイルは以下にまとめました
https://github.com/cloudnativedaysjp/dreamkast-broadcast/tree/main/sandbox/chago/20210206

**Comment by TakumaNakagame** [comment]
以下、@jacopen さん対応により、VNCの高速化（GPU利用）を解決した。

- VNC + XRDP利用では、デスクトップ描画にGPUを利用することが難しい状況だった
- 対し、VNCを利用した場合はこれを回避でき、問題なくデスクトップ描画にGPUを利用してくれた
  - https://cloudnativedays.slack.com/archives/C01M687CZ7S/p1612685720085700
- これにより、g4dn.xlargeでも問題なく配信が可能となった

@jacopen さん作のスクリプト
https://github.com/cloudnativedaysjp/dreamkast-broadcast/blob/main/sandbox/jacopen/memo.md

**Comment by jacopen** [comment]
検証に使ったVNCクライアントはUltraVNCです。
https://forest.watch.impress.co.jp/library/software/ultravnc/

が、VNCであればどのクライアントでも良いと思われます。

↑で共有してくれたセットアップ方法だとPort 5900を利用しますんで、Security Groupの設定でTCPおよびUDP5900を開けるようにしてください

**Comment by chago0419** [comment]
Ubuntu Server 20.04 LTS (HVM), SSD Volume Type - ami-0e039c7d64008bd84 (64 ビット x86) / ami-02217e84754fa6122 (64 ビット Arm)
g4dn.xlarge 

https://aws.amazon.com/jp/ec2/spot/pricing/
リージョン東京だと **$0.213 /1 時間** (Linux/UNIX 料金)
