### ISSUE TITLE
PC以外の周辺機器で必要なものを検討する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#61]
選定は @TakumaNakagame で行い、実際の発注は @jacopen が行う。
なお、荷物搬送の都合上、配送先は @TakumaNakagame となる。

必要なものは以下

- [x] リモート部屋用スイッチ x 2
    - 3ポート以上のもの
    - WebUIによる制御やトラフィックモニタリングができるもの
- [x] LANケーブル x 24
    - [x] Long(20m) x 5
    - [x] Short(5m) x 19
- [ ] モバイルデバイス用NIC x 2
    - TypeC対応

**Comment by jacopen** [comment]
よさそう。これでいこう

**Comment by TakumaNakagame** [comment]
| 品名 | 個数 | 単価 | 計 | 
| --- | ---: | ---: | ---: |
| LAN-1200(BL) | 5 本 | 2,189円 | 10,945円 |
| LAN-1050(BL) | 19 本 | 912円 | 17,328円 |
| GS308T | 2 個 | 5,918円 | 11,836円 |

合計： 40,109円

**Comment by TakumaNakagame** [comment]
USB NICについては23日の作業時に購入するためスキップ
