### ISSUE TITLE
Zoom Rooms -> OBSでNDI入力した際、回線状況によって画面共有のサイズが変わってしまう

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-broadcast#71]
10/24の検証で発覚。

どうやらZoomはクライアント側の回線状況によって、画面共有も解像度を下げることによってビットレートを引き下げる仕組みになっている様子。

NDI Outputを使うと、NDI側でSourceの解像度が動的に変わってしまうため、OBSで画面構成をしても大きくなったり小さくなったりして非常に気になる。

この問題について対処する

**Comment by TakumaNakagame** [comment]
画面キャプチャ構成を行うことで解消する。
構成は以下のIssueにて
https://github.com/cloudnativedaysjp/dreamkast-broadcast/issues/110
