### ISSUE TITLE
当日のタイムラインを作成する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#76]
紙で印刷して各自持っておきたいやつ
以下が分かるとよい

- 各日全体の流れや、担当者の動き
- 各時間で利用する設備等の稼働状況（特にスタジオやリモート部屋）

**Comment by capsmalt** [comment]
@KaseiKondo ちょくちょく更新してますが、配信全体に合わせて記載しました。
https://docs.google.com/presentation/d/1aB7iHU-WL1rCe7UF2w1Hkafx8e5GzSZF/edit#slide=id.p7

実行委員についても、チーム単位ではなく、当日のタスク単位で管理できるように「TASK列」を用意しました。
https://docs.google.com/spreadsheets/d/1tL4uizzfyyBSpTk8udDO3aq8fhTIV8DmRlkGFFef9Fo/edit#gid=1433115253
