### ISSUE TITLE
【ただいま動画の変換中です】動画を作る

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-broadcast#83]

**Comment by Gaku-Kunimi** [comment]
https://stock.adobe.com/jp/search/free?k=under+construction&search_type=usertyped&asset_id=284810520
かわいい無料素材があったので、これでできそう

**Comment by Gaku-Kunimi** [comment]
11/2 夜 制作予定

**Comment by Gaku-Kunimi** [comment]
## 成果物
変換中
https://drive.google.com/file/d/1DhGpSymINQirg-EWK4_ZzuzRKYj33r_D/view?usp=sharing

調整中(ついでに)
https://drive.google.com/file/d/1s6eGML46x2uWFSdBtKOBoDfRzmDkjisd/view?usp=sharing
