### ISSUE TITLE
リモート部屋用の登壇者リストを作成する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#84]
各登壇者の一覧と、利用するOBSのシーンや注意点を記載したリストを作成する
ベースは以下のスプシを利用する
https://docs.google.com/spreadsheets/d/1GNVTsDyAsblcWej1mkJzTl2djy86ZrGSeSyrkZQbH5I/edit#gid=2099065606

**Comment by TakumaNakagame** [comment]
最終的には、紙に印刷して各部屋に起きたい

**Comment by nabemasat** [comment]
@TakumaNakagame 
こちらセッション時間、トラックなどの情報を追記しました。
Zoomの部屋名がトラックになっているので、リモート1、リモート2と対応するように変更していただけますか？

**Comment by TakumaNakagame** [comment]
こちら、対応完了しました🙋
