### ISSUE TITLE
各種素材の置き場所を考える

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#91]
対象となるファイルは以下の通り

- 画像素材
- BGM等
- 動画素材

`画像素材`については、Creative CloudのCloud Storageを利用する → @jacopen さんのストレージを共有
その他、BGMや動画素材については、容量が大きいためAdobe CCは利用できない。
これらの動画の保管場所について検討する

**Comment by jacopen** [comment]
とりあえずさくら環境にnextcloud入れてみるかねー

**Comment by TakumaNakagame** [comment]
そうしましょうか
一旦作ってみて、使い勝手とかフィードバックしましょう

**Comment by TakumaNakagame** [comment]
以下の通り
ref: https://docs.google.com/document/d/1j5RAuTlYBTAfmPQL0weU73pc4ZH-Zy3ffuH6OK1Xj98/edit#heading=h.46n8n3w089c

### Google Drive
- 各種ドキュメント
- 一時的な動画データなど

### NextCloud
- 原則動画データ
- 録画データ
- CMや幕間などの出力されたデータ
- 幕間のプロジェクトデータ

### Creative Cloud
- ロゴや背景等のデータ
