### ISSUE TITLE
レンタルPC等の一時保管について

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#92]
2月26日～3月11日まで、一時的にレンタルPC等を保管する場所を決める必要がある。

当初の予定では、@takumanakagame 宅に一時的に配置する予定だったが、万が一 @TakumaNakagame が新型コロナウイルスに感染してしまって当日来れなくなった場合、このPCの確保が非常に難しくなる。
そのため、これの対策等を検討する必要がある。

**Comment by TakumaNakagame** [comment]
理想は、誰か一人ではなく、複数人がアクセスできるような場所に保管するのが良い。
たとえば、共用の倉庫などやオフィスなどがあれば、そこにおいておき、感染者が出た場合でも他の人が取りにいける。

**Comment by jacopen** [comment]
@ito-taka @nabemasat このPCの保管場所、インプレスを使わせて貰うことは可能でしょうか？

**Comment by nabemasat** [comment]
@jacopen 
インプレスを置き場に使うこと自体は可能かと思いますが、会場に何日か前に置ければ、その方が便利かと思います。具体的な部分は @KaseiKondo  交えて下記のスレでやり取り中です
https://cloudnativedays.slack.com/archives/C0204MGK6V6/p1645665693499529

**Comment by TakumaNakagame** [comment]
↑での議論の結果、会場で26日～11日預かってもらえることになった。
よって本問題は解消されたのでCloseとする
